### ISSUE TITLE
The size of tensor a (64) must match the size of tensor b (128) at non-singleton dimension 1

### ISSUE THREAD

**Issue by FuHui-UPC** [aliyun/3D-Local-CNN-for-Gait-Recognition#3]
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    p.start()
  File "/home/fh/3D-Local-CNN-for-Gait-Recognition/solvers/solver.py", line 55, in start
    return mode()
  File "/home/fh/3D-Local-CNN-for-Gait-Recognition/solvers/baseline.py", line 95, in train
    feature = self.model(seq)
  File "/home/fh/miniconda3/envs/gait/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fh/miniconda3/envs/gait/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/fh/miniconda3/envs/gait/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fh/3D-Local-CNN-for-Gait-Recognition/models/localcnn3d.py", line 302, in forward
    gl = self.local(feat4_5d, feat6_5d)
  File "/home/fh/miniconda3/envs/gait/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fh/3D-Local-CNN-for-Gait-Recognition/models/localcnn3d.py", line 166, in forward
    head = self.head(x, param_x.detach())
  File "/home/fh/miniconda3/envs/gait/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fh/3D-Local-CNN-for-Gait-Recognition/models/localcnn3d.py", line 121, in forward
    sampled_feature = self.sampler(x, loc_params)
  File "/home/fh/miniconda3/envs/gait/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fh/3D-Local-CNN-for-Gait-Recognition/models/sample.py", line 233, in forward
    glimpse = torch.matmul(Fyv, torch.matmul(x, Fxt))
RuntimeError: The size of tensor a (64) must match the size of tensor b (128) at non-singleton dimension 1

I met some errors when I run "python main.py --config=configs/3DLocalCNN_CASIA.yaml". Could you help me?

**Comment by X-ray0214** [comment]
Have you ever solved the problem? I met the same error now.

**Comment by FuHui-UPC** [comment]
> Have you ever solved the problem? I met the same error now.

No. It must be the error of the provided source code.

**Comment by Yangyc07** [comment]
> 

请问你解决该问题了吗，数据预处理的程序好像运行不了

**Comment by FuHui-UPC** [comment]
> > 
> 
> 请问你解决该问题了吗，数据预处理的程序好像运行不了

没有解决，联系作者也没有回复，数据预处理好像没有问题吧

**Comment by Yangyc07** [comment]
> 

这个预处理和gaitset不同，请问怎么运行pretrement文件预处理

**Comment by HUAFOR** [comment]
我也是遇到了这个问题！作者可以回复一下吗？

**Comment by zhang123-sys** [comment]
一定cuda10.2？cuda11.1可以吗？

**Comment by hxi667** [comment]
> 我也是遇到了这个问题！作者可以回复一下吗？

你是因为多个GPU吧，我也遇到了这种问题。但是只用一张GPU的话就没问题
